#!/bin/bash -l
#PBS -l walltime=1:00:00,pmem=7Gb,nodes=4:ppn=1
#PBS -m abe

module unload intelmpi
module load pathmpi

cd $PBS_O_WORKDIR

mpirun -np 4 -hostfile $PBS_NODEFILE ./ngram $ROOT $UCUTOFF $ACUTOFF $IFILE > output




