#!/bin/bash -l
#PBS -l walltime=03:00:00,pmem=1Gb,nodes=1:ppn=4
#PBS -m abe

module unload intelmpi
module load pathmpi

cd $PBS_O_WORKDIR

mpirun -np 4 -hostfile $PBS_NODEFILE ./ngram $ROOT $UCUTOFF $ACUTOFF $IFILE > output


